/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedText: typeof import('./src/components/animated-text/AnimatedText.vue')['default']
    Button: typeof import('primevue/button')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Corgi: typeof import('./src/components/corgi/Corgi.vue')['default']
    FadeIn: typeof import('./src/components/animations/FadeIn.vue')['default']
    LandingCard: typeof import('./src/components/landing-card/LandingCard.vue')['default']
    Pill: typeof import('./src/components/Pill/Pill.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SlideInDown: typeof import('./src/components/animations/SlideInDown.vue')['default']
  }
}
